modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0-only"

[[mods]] #mandatory
# The modid of the mod
modId="lycoris" #mandatory
version="${version}" #mandatory
 # A display name for the mod
displayName="Lycoris" #mandatory
logoFile="iris-logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="coderbot,IMS212,Justsnoopy30,FoundationGames,SQwatermark(Forge Porter)" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs
Lycoris is a forge ported version of Iris by SQwatermark.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.lycoris]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.lycoris]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
